### ISSUE TITLE
ModuleNotFoundError: No module named 'examples'

### ISSUE THREAD

**Issue by rumourscape** [Speech-Lab-IITM/Fairseq-Inference#1]
![image](https://github.com/Speech-Lab-IITM/Fairseq-Inference/assets/56497189/b293d23b-6c51-4d6f-9baa-e858081a21b1)
Image for reference.

**Comment by monalipb** [comment]
How you resolved it? @rumourscape

**Comment by rumourscape** [comment]
Yep

**Comment by monalipb** [comment]
Can you say how you resolved it? @rumourscape
